/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import classes.Aeroporto;
import classes.Aviao;

/**
 *
 * @author Modusaleatorios
 */
public class AirplanePropertiesPanel extends javax.swing.JPanel
{

    /**
     * Creates new form AirplanePropertiesPanel
     */
    public AirplanePropertiesPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtAirplaneName = new javax.swing.JTextField();
        lblAirplaneAirportName = new javax.swing.JLabel();
        txtAirplaneAirportName = new javax.swing.JTextField();
        lblAirplaneModelName = new javax.swing.JLabel();
        txtAirplaneModelName = new javax.swing.JTextField();
        lblVelocidadeCruzeiro = new javax.swing.JLabel();
        txtVelocidadeCruzeiro = new javax.swing.JTextField();
        lblAltitudeCruzeiro = new javax.swing.JLabel();
        txtAltitudeCruzeiro = new javax.swing.JTextField();
        lblDistanciaMax = new javax.swing.JLabel();
        txtDistanciaMax = new javax.swing.JTextField();
        lblPassageirosMax = new javax.swing.JLabel();
        txtPassageirosMax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCombustivelMax = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblAltitudeViajadaMax = new javax.swing.JLabel();
        txtAltitudeViajadaMax = new javax.swing.JTextField();
        lblDistanciaViajadaMax = new javax.swing.JLabel();
        txtDistanciaViajadaMax = new javax.swing.JTextField();
        lblPassageirosTransportadosMax = new javax.swing.JLabel();
        txtPassageirosTransportadosMax = new javax.swing.JTextField();

        setBackground(new java.awt.Color(229, 242, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Airplane Properties"));
        setPreferredSize(new java.awt.Dimension(380, 390));

        txtAirplaneName.setEditable(false);
        txtAirplaneName.setBackground(new java.awt.Color(203, 229, 255));
        txtAirplaneName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lblAirplaneAirportName.setText("In Airport");

        txtAirplaneAirportName.setEditable(false);
        txtAirplaneAirportName.setBackground(new java.awt.Color(219, 237, 255));

        lblAirplaneModelName.setText("Airplane Model");

        txtAirplaneModelName.setEditable(false);
        txtAirplaneModelName.setBackground(new java.awt.Color(219, 237, 255));

        lblVelocidadeCruzeiro.setText("Cruise Velocity");

        txtVelocidadeCruzeiro.setEditable(false);
        txtVelocidadeCruzeiro.setBackground(new java.awt.Color(219, 237, 255));

        lblAltitudeCruzeiro.setText("Cruise Altitude");

        txtAltitudeCruzeiro.setEditable(false);
        txtAltitudeCruzeiro.setBackground(new java.awt.Color(219, 237, 255));

        lblDistanciaMax.setText("Maximum Distance");

        txtDistanciaMax.setEditable(false);
        txtDistanciaMax.setBackground(new java.awt.Color(219, 237, 255));

        lblPassageirosMax.setText("Maximum Passengers");

        txtPassageirosMax.setEditable(false);
        txtPassageirosMax.setBackground(new java.awt.Color(219, 237, 255));

        jLabel1.setText("Maximum Fuel");

        txtCombustivelMax.setEditable(false);
        txtCombustivelMax.setBackground(new java.awt.Color(219, 237, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblAltitudeViajadaMax.setText("Maximum Altitude Flown");

        txtAltitudeViajadaMax.setEditable(false);

        lblDistanciaViajadaMax.setText("Maximum Distance Flown");

        txtDistanciaViajadaMax.setEditable(false);

        lblPassageirosTransportadosMax.setText("Maximum Passengers Carried");

        txtPassageirosTransportadosMax.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassageirosTransportadosMax)
                    .addComponent(lblDistanciaViajadaMax)
                    .addComponent(lblAltitudeViajadaMax))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltitudeViajadaMax, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(txtDistanciaViajadaMax)
                    .addComponent(txtPassageirosTransportadosMax))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltitudeViajadaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltitudeViajadaMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistanciaViajadaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDistanciaViajadaMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassageirosTransportadosMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassageirosTransportadosMax))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Performance", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAirplaneAirportName)
                        .addGap(18, 18, 18)
                        .addComponent(txtAirplaneAirportName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassageirosMax)
                            .addComponent(lblDistanciaMax)
                            .addComponent(jLabel1)
                            .addComponent(lblAltitudeCruzeiro)
                            .addComponent(lblVelocidadeCruzeiro)
                            .addComponent(lblAirplaneModelName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassageirosMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDistanciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCombustivelMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAltitudeCruzeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVelocidadeCruzeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAirplaneModelName)))
                    .addComponent(txtAirplaneName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAirplaneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirplaneAirportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAirplaneAirportName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirplaneModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAirplaneModelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVelocidadeCruzeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVelocidadeCruzeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltitudeCruzeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAltitudeCruzeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistanciaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDistanciaMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassageirosMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassageirosMax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCombustivelMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    public void setAirplane(Aviao aviao, Aeroporto aeroporto)
    {
        this.airplane = aviao;
        this.txtAirplaneName.setText(this.airplane.getNomeAviao() + "   [ " + this.airplane.getMyCompanhiaAerea().getNome() + " ]");
        this.txtAirplaneAirportName.setText(aeroporto.getNome());
        this.txtAirplaneModelName.setText(this.airplane.getMyModeloAviao().getNome());
        this.txtVelocidadeCruzeiro.setText(this.airplane.getMyModeloAviao().getVelocidadeCruzeiro() + " km/h");
        this.txtAltitudeCruzeiro.setText(this.airplane.getMyModeloAviao().getAltitudeCruzeiro() + " m");
        this.txtDistanciaMax.setText(this.airplane.getMyModeloAviao().getDistanciaMax() + " km");
        this.txtPassageirosMax.setText(this.airplane.getMyModeloAviao().getPassageirosMax() + " pax");
        this.txtCombustivelMax.setText(this.airplane.getMyModeloAviao().getCombustivelMax() + " lt");
    }
    
    public void setAirportMaximumAltitudeFlown(Integer airportMaximumAltitudeFlown)
    {
        this.txtAltitudeViajadaMax.setText(airportMaximumAltitudeFlown.toString() + " km");
    }
    
    public void setAirplaneMaximumDistanceFlown(Integer airplaneMaximumDistanceFlown)
    {
        this.txtDistanciaViajadaMax.setText(airplaneMaximumDistanceFlown.toString() + " km");
    }
    
    public void setAirplaneMaximumPassengersCarried(Integer airplaneMaximumPassengersCarried)
    {
        this.txtPassageirosTransportadosMax.setText(airplaneMaximumPassengersCarried.toString() + " pax");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAirplaneAirportName;
    private javax.swing.JLabel lblAirplaneModelName;
    private javax.swing.JLabel lblAltitudeCruzeiro;
    private javax.swing.JLabel lblAltitudeViajadaMax;
    private javax.swing.JLabel lblDistanciaMax;
    private javax.swing.JLabel lblDistanciaViajadaMax;
    private javax.swing.JLabel lblPassageirosMax;
    private javax.swing.JLabel lblPassageirosTransportadosMax;
    private javax.swing.JLabel lblVelocidadeCruzeiro;
    private javax.swing.JTextField txtAirplaneAirportName;
    private javax.swing.JTextField txtAirplaneModelName;
    private javax.swing.JTextField txtAirplaneName;
    private javax.swing.JTextField txtAltitudeCruzeiro;
    private javax.swing.JTextField txtAltitudeViajadaMax;
    private javax.swing.JTextField txtCombustivelMax;
    private javax.swing.JTextField txtDistanciaMax;
    private javax.swing.JTextField txtDistanciaViajadaMax;
    private javax.swing.JTextField txtPassageirosMax;
    private javax.swing.JTextField txtPassageirosTransportadosMax;
    private javax.swing.JTextField txtVelocidadeCruzeiro;
    // End of variables declaration//GEN-END:variables
    private Aviao airplane;
}
