/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import graphs.ConnectedComponents;
import graphs.EdgeWeightedSymbolDigraph;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Modusaleatorios
 */
public class GraphConexPanel extends javax.swing.JPanel
{

    /**
     * Creates new form GraphConexPanel
     */
    public GraphConexPanel()
    {
        initComponents();
        
        this.lst_ListConnections.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbl_TotalNumberAirports = new javax.swing.JLabel();
        txt_TotalNumberAirports = new javax.swing.JTextField();
        lbl_NumberIslandComponents = new javax.swing.JLabel();
        txt_NumberIslandComponents = new javax.swing.JTextField();
        lbl_ConexStatus = new javax.swing.JLabel();
        txt_ConexStatus = new javax.swing.JTextField();
        ScrollPane_ListConnections = new javax.swing.JScrollPane();
        lst_ListConnections = new javax.swing.JList<>();

        setBackground(new java.awt.Color(224, 239, 255));

        lbl_TotalNumberAirports.setText("TOTAL NUMBER OF AIRPORTS");

        txt_TotalNumberAirports.setEditable(false);
        txt_TotalNumberAirports.setBackground(new java.awt.Color(219, 237, 255));
        txt_TotalNumberAirports.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_NumberIslandComponents.setText("Number of Island Components");

        txt_NumberIslandComponents.setEditable(false);
        txt_NumberIslandComponents.setBackground(new java.awt.Color(219, 237, 255));

        lbl_ConexStatus.setText("CONNECTED");

        txt_ConexStatus.setEditable(false);
        txt_ConexStatus.setBackground(new java.awt.Color(203, 229, 255));
        txt_ConexStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_ConexStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lst_ListConnections.setBackground(new java.awt.Color(219, 237, 255));
        lst_ListConnections.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollPane_ListConnections.setViewportView(lst_ListConnections);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_ListConnections)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TotalNumberAirports)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TotalNumberAirports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(lbl_NumberIslandComponents)
                        .addGap(18, 18, 18)
                        .addComponent(txt_NumberIslandComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                        .addComponent(lbl_ConexStatus)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ConexStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TotalNumberAirports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TotalNumberAirports)
                    .addComponent(lbl_NumberIslandComponents)
                    .addComponent(txt_NumberIslandComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ConexStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ConexStatus))
                .addGap(18, 18, 18)
                .addComponent(ScrollPane_ListConnections, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setConexBoard(EdgeWeightedSymbolDigraph ewSymbolDigraph)
    {
        this.cc = new ConnectedComponents(ewSymbolDigraph.getEdgeWeightedDirectedGraph());
        String[] listData = new String[ewSymbolDigraph.getEdgeWeightedDirectedGraph().getNumberOfVertices()];
        
        setTotalNumberAirports(ewSymbolDigraph.getEdgeWeightedDirectedGraph().getNumberOfVertices());
        setNumberIslandComponents(this.cc.getCount());
        setConexStatus(this.cc.conexo());
        
        for (int v = 0; v < ewSymbolDigraph.getEdgeWeightedDirectedGraph().getNumberOfVertices(); v++)
        {
            String listLine = ewSymbolDigraph.nameOf(v) + " (" + this.cc.getSize(v) + ") -> ";
            
            for (int i = 0; i < this.cc.getSize(v); i++)
            {
                if (cc.connected(v, i))
                {
                    listLine = listLine + "   " + ewSymbolDigraph.nameOf(i);
                }
            }
            listData[v] = listLine;
        }
        this.lst_ListConnections.setListData(listData);
    }
    
    /**Sets the total number of airports in the weighted directed graph.
     * @param numberAirports the number of airports/vertices
     */
    public void setTotalNumberAirports(Integer numberAirports)
    {
        this.txt_TotalNumberAirports.setText(numberAirports.toString());
    }
    
    /**Sets the number of islands components in this weighted directed graph
     * @param numberIsland the number of island/connected components.
     */
    public void setNumberIslandComponents(Integer numberIsland)
    {
        this.txt_NumberIslandComponents.setText(numberIsland.toString());
    }
    
    /**Sets boolean value to verify that the graph is connected.
     * @param conexStatus {@code true} sets the text to "yes", and {@code flase} sets the text to "no".
     */
    public void setConexStatus(boolean conexStatus)
    {
        if (conexStatus)
        {
            this.txt_ConexStatus.setText("YES");
        }
        else
        {
            this.txt_ConexStatus.setText("NO");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane_ListConnections;
    private javax.swing.JLabel lbl_ConexStatus;
    private javax.swing.JLabel lbl_NumberIslandComponents;
    private javax.swing.JLabel lbl_TotalNumberAirports;
    private javax.swing.JList<String> lst_ListConnections;
    private javax.swing.JTextField txt_ConexStatus;
    private javax.swing.JTextField txt_NumberIslandComponents;
    private javax.swing.JTextField txt_TotalNumberAirports;
    // End of variables declaration//GEN-END:variables

    private ConnectedComponents cc;
}
